# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  Build.SourcesDirectory: /catalog-api

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm ci
    npm run build
    npm test
  displayName: 'npm install and build'
  workingDirectory: '/home/vsts/work/1/s/catalog-api'

- task: CopyFiles@2
  inputs:
    contents: '/home/vsts/work/1/s/catalog-api/package.json' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy package.json'

- task: CopyFiles@2
  inputs:
    contents: '/home/vsts/work/1/s/catalog-api/package-lock.json' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy package-lock.json'

- task: CopyFiles@2
  inputs:
    contents: '/home/vsts/work/1/s/catalog-api/app.js' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy app.js'

- task: CopyFiles@2
  inputs:
    contents: '/home/vsts/work/1/s/catalog-api/bin/*' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy bin folder'

- task: CopyFiles@2
  inputs:
    contents: '/home/vsts/work/1/s/catalog-api/routes/*' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm
  displayName: 'Copy routes folder'

- task: PublishBuildArtifacts@1
  displayName: 'Publish npm artifacts'
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)/npm
    ArtifactName: 'npm'
    publishLocation: 'Container'
